import os
import smtplib
from email.message import EmailMessage
from reportlab.lib.pagesizes import letter, A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image
from reportlab.lib import colors
from datetime import datetime
import textwrap

def generate_pdf_report(dummy_input=""):
    """Reads the last audit log and generates a PDF file."""
    try:
        # Read the audit result from temp file
        with open("temp_audit_log.txt", "r", encoding="utf-8") as f:
            content = f.read()
            
        pdf_filename = "Audit_Report.pdf"
        
        # Create PDF with better formatting
        c = canvas.Canvas(pdf_filename, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawString(72, height - 72, "Skeptic Analyst - Audit Report")
        
        # Date
        c.setFont("Helvetica", 10)
        c.drawString(72, height - 95, f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
        
        # Divider line
        c.setStrokeColorRGB(0.2, 0.4, 0.8)
        c.setLineWidth(2)
        c.line(72, height - 105, width - 72, height - 105)
        
        # Content
        c.setFont("Helvetica", 11)
        text_object = c.beginText(72, height - 140)
        text_object.setLeading(16)
        
        # Split text by lines to prevent overflow
        for line in content.split("\n"):
            # Wrap long lines
            wrapped_lines = textwrap.wrap(line, width=85)
            if wrapped_lines:
                for wrapped_line in wrapped_lines:
                    text_object.textLine(wrapped_line)
            else:
                text_object.textLine("")  # Empty line
            
        c.drawText(text_object)
        
        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(72, 50, "Confidential - Generated by Skeptic Analyst Agent")
        
        c.save()
        
        return f"✅ SUCCESS: Report generated as '{pdf_filename}'. You can download it now."
    
    except FileNotFoundError:
        return "❌ ERROR: No audit has been run yet. Please run an audit first."
    except Exception as e:
        return f"❌ ERROR generating PDF: {str(e)}"


def generate_analysis_pdf(analysis_text: str):
    """
    Generates a professional PDF report for Deep Dive Text Analysis.
    
    Args:
        analysis_text: The full text analysis from Step 5 Option 1
    """
    try:
        pdf_filename = "Deep_Dive_Analysis.pdf"
        
        # Create document
        doc = SimpleDocTemplate(pdf_filename, pagesize=letter,
                                leftMargin=72, rightMargin=72,
                                topMargin=72, bottomMargin=72)
        
        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#1e40af'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        body_style = ParagraphStyle(
            'CustomBody',
            parent=styles['BodyText'],
            fontSize=11,
            leading=16,
            spaceAfter=10
        )
        
        # Build content
        story = []
        
        # Title
        story.append(Paragraph("Deep Dive Analysis Report", title_style))
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}", 
                               styles['Normal']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Divider
        story.append(Spacer(1, 0.1 * inch))
        
        # Process analysis text
        sections = analysis_text.split('**')
        
        for i, section in enumerate(sections):
            section = section.strip()
            if not section:
                continue
            
            # Check if this is a heading (ends with :)
            if section.endswith(':'):
                story.append(Paragraph(section, heading_style))
            else:
                # Regular paragraph
                # Replace markdown-style bullets with proper formatting
                lines = section.split('\n')
                for line in lines:
                    line = line.strip()
                    if line:
                        # Handle bullet points
                        if line.startswith('- ') or line.startswith('* ') or line.startswith('✓'):
                            line = '• ' + line[2:]
                        story.append(Paragraph(line, body_style))
        
        # Footer
        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=9,
            textColor=colors.grey,
            alignment=1
        )
        story.append(Paragraph("Confidential - Generated by Skeptic Analyst Agent", footer_style))
        
        # Build PDF
        doc.build(story)
        
        return f"✅ Analysis PDF generated: {pdf_filename}"
        
    except Exception as e:
        return f"❌ Error generating analysis PDF: {str(e)}"


def generate_dashboard_pdf():
    """
    Generates a PDF report from the dashboard HTML file.
    Uses kaleido to convert Plotly charts to images.
    """
    try:
        html_path = "dashboard_report.html"
        
        if not os.path.exists(html_path):
            return "❌ Error: dashboard_report.html not found. Generate dashboard first."
        
        pdf_filename = "Dashboard_Report.pdf"
        
        # Method 1: Try using plotly's kaleido (best quality)
        try:
            import plotly.graph_objects as go
            from plotly.io import write_image
            import duckdb
            from visualization_tools import session as viz_session
            
            # Recreate the dashboard figure
            if not os.path.exists("warehouse.db"):
                return "❌ Error: Database not found."
            
            conn = duckdb.connect("warehouse.db", read_only=True)
            
            # Get basic info for title
            fact_table = "fact_table"
            row_count = conn.execute(f"SELECT COUNT(*) FROM {fact_table}").fetchone()[0]
            
            conn.close()
            
            # Generate static image
            fig = viz_session.generate_dashboard_figure()  # We'll add this method
            
            if fig:
                # Save as high-quality PNG first
                temp_img = "dashboard_temp.png"
                fig.write_image(temp_img, width=1200, height=900, scale=2)
                
                # Create PDF with image
                c = canvas.Canvas(pdf_filename, pagesize=A4)
                width, height = A4
                
                # Header
                c.setFont("Helvetica-Bold", 18)
                c.drawString(50, height - 50, "Dashboard Report")
                
                c.setFont("Helvetica", 10)
                c.drawString(50, height - 70, f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
                c.drawString(50, height - 85, f"Total Records Analyzed: {row_count:,}")
                
                # Insert dashboard image
                c.drawImage(temp_img, 50, height - 700, width=500, height=375, preserveAspectRatio=True)
                
                # Footer
                c.setFont("Helvetica-Oblique", 9)
                c.drawString(50, 40, "Confidential - Generated by Skeptic Analyst Agent")
                
                c.save()
                
                # Cleanup temp image
                if os.path.exists(temp_img):
                    os.remove(temp_img)
                
                return f"✅ Dashboard PDF generated: {pdf_filename}"
            
        except ImportError:
            # Fallback: Use simple text-based PDF
            pass
        
        # Method 2: Fallback - Create text-based PDF with summary
        c = canvas.Canvas(pdf_filename, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 20)
        c.drawString(72, height - 72, "Dashboard Report")
        
        c.setFont("Helvetica", 10)
        c.drawString(72, height - 95, f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
        
        # Divider
        c.setStrokeColorRGB(0.2, 0.4, 0.8)
        c.setLineWidth(2)
        c.line(72, height - 105, width - 72, height - 105)
        
        # Content
        c.setFont("Helvetica", 11)
        text_y = height - 140
        
        c.drawString(72, text_y, "📊 Interactive Dashboard Available")
        text_y -= 30
        
        c.setFont("Helvetica", 10)
        c.drawString(72, text_y, "For the full interactive experience with charts and visualizations,")
        text_y -= 15
        c.drawString(72, text_y, "please open: dashboard_report.html")
        text_y -= 30
        
        c.drawString(72, text_y, "This PDF serves as a static record of the analysis.")
        text_y -= 15
        c.drawString(72, text_y, "All interactive features are available in the HTML version.")
        
        # Footer
        c.setFont("Helvetica-Oblique", 9)
        c.drawString(72, 50, "Confidential - Generated by Skeptic Analyst Agent")
        
        c.save()
        
        return f"✅ Dashboard PDF generated: {pdf_filename} (Open dashboard_report.html for interactive version)"
        
    except Exception as e:
        return f"❌ Error generating dashboard PDF: {str(e)}"


def send_email_report(recipient_email: str):
    """
    Sends the 'Audit_Report.pdf' to the specified email.
    NOTE: This is a MOCK implementation for testing.
    """
    pdf_filename = "Audit_Report.pdf"
    
    # Check if PDF exists
    if not os.path.exists(pdf_filename):
        return "❌ ERROR: PDF report not found. Please generate PDF first."
    
    # MOCK EMAIL (Real SMTP commented out for safety)
    print(f"\n[SYSTEM] 📧 MOCK EMAIL SENT TO: {recipient_email}")
    print(f"[SYSTEM] 📎 ATTACHMENT: {pdf_filename}")
    
    return f"✅ SIMULATION: Email queued for {recipient_email} (Check terminal output)."

# REAL EMAIL IMPLEMENTATION (Uncomment to use):
# 
# import os
# 
# def send_email_report(recipient_email: str):
#     """Sends audit report via email using SMTP."""
#     pdf_filename = "Audit_Report.pdf"
#     
#     # Read PDF
#     try:
#         with open(pdf_filename, "rb") as f:
#             pdf_data = f.read()
#     except FileNotFoundError:
#         return "❌ ERROR: PDF report not found."
#     
#     # Get credentials from environment
#     sender = os.getenv("EMAIL_USER")
#     password = os.getenv("EMAIL_PASS")
#     
#     if not sender or not password:
#         return "❌ ERROR: EMAIL_USER or EMAIL_PASS not set in .env"
#     
#     # Send email
#     try:
#         msg = EmailMessage()
#         msg['Subject'] = 'Skeptic Analyst Audit Report'
#         msg['From'] = sender
#         msg['To'] = recipient_email
#         msg.set_content("Please find the attached audit report from Skeptic Analyst.")
#         msg.add_attachment(pdf_data, maintype='application', subtype='pdf', filename=pdf_filename)
#         
#         with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
#             smtp.login(sender, password)
#             smtp.send_message(msg)
#         
#         return f"✅ SUCCESS: Email sent to {recipient_email}"
#     except Exception as e:
#         return f"❌ ERROR sending email: {e}"